default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
    gym(scheme: "Runner")
    deliver(skip_screenshots: true, skip_metadata: true)
  end
end