name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Setup Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.9'
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Create Artefact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          tar -czf /tmp/${GITHUB_SHA}.tar.gz --exclude=.git --exclude=.github .
          mv /tmp/${GITHUB_SHA}.tar.gz .

      - uses: actions/upload-artifact@v4
        with:
          name: app-setup
          path: ./${{ github.sha }}.tar.gz
          retention-days: 0

  lint-test:
    needs: [setup]
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-setup
          path: ./

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.9'
          channel: stable
          cache: true

      - name: Extract Artefact
        run: tar -xzf ./${{ github.sha }}.tar.gz -C .

      - name: Analyze code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

  build-android:
    needs: [lint-test]
    name: Build Android APK
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.9'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS for TestFlight
    runs-on: macos-latest
    needs: [lint-test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.9'

      - name: Install Ruby (for Fastlane)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundle-cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && bundle install

      - name: Flutter build ipa
        run: |
          flutter build ipa --no-codesign

      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/ios_build.tar.gz

  clean-up:
    name: Clean up
    runs-on: ubuntu-latest
    needs: [build-ios,build-android]
    if: ${{ always() }}
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: app-setup